////////////////////////////////////////////////
/////// Find out when user cluster was touched 
////////////////////////////////////////////////


/////// Find out when nsenter were created /////

https://dataexplorer.azure.com/clusters/aks/databases/AKSccplogs?query=H4sIAAAAAAAAA31Sy27bMBC8+ysIX2QBkvWI/Dq4gOsGgZE+Ars9BxS5kulIpEpSbgz047tSbMlI0lwkYGd2dna4tRRKkrWSVqvioaASbo8grfHelr4rudsrSNXz4C/5swcN5EEDEwZ+ihJ2lpYV+URorkbJ3h0EwYWkwahaM9hwsqeGOIGpU8O0qCyONsFNRHm6SKnPKWd+MpvP/DlkM5+xJJuG2SK+mUJw0ci1qisT3K8+b7Zff3y5u/W3d0Gl1VFw0Cb4JphWRmV23NinQoLegT4KBkFJJc2Br4va2IZ6JbG638XOlWFJSzAVZUDYi4ohwwmwSchZFM/SbDINwzCaxmEynw+v+tBHBdoKMH2jI3Tl89QvaTPWP6jUP1eYsGCsH4dxFEWLaDJJksjX86fy4Aw+Uhxu0RwGB2tVVgVYGH5MDyrFTYB8iQYaLjxbkPxCPpElsYqfcGnBRr2C2zNpzYVFWkW1gceDUXJklbFayPzScBoXKnebHiwcgNk3p+ER9OERRi3kSp88PIvfNQbwa7tZdmrtpHGPuB45gk5fE5oaQsZSWxsEhbRd60s2uxYaM8UBibUBvcoxgNdCHXAmvYe3n+YkXK9A85Kdlhz/Fhd75CLLRk4pigJXxci54zVhnuGzCNrM2xxMk4P7DuO88BYYiCPwnovkltG9cLM5EZKMHKYBRRyXdFi3zNXjP9UpPkbRn0if7X9P5B/Bvt3rEwQAAA==

union ControlPlaneEvents,ControlPlaneEventsNonShoebox
| where PreciseTimeStamp > ago(4h)
//| where resourceId has '/subscriptions/31adb9ba-dadc-4787-8ef7-cc4f60f9236e/resourcegroups/KABIRLODGE-RG/providers/Microsoft.ContainerService/managedClusters/KABIRLODGE-AKS2'
//| where namespace contains "5ec50dc127bf560001620488"
//| where properties contains 'irp-db-master-job-irp-db-citest-2021119155441-r8kmj'
| where properties contains "ResponseComplete"
| where properties contains "/pods/nsenter"
| extend property = todynamic(properties)
| extend audit = parse_json(tostring(property.log))
| project PreciseTimeStamp, pod, category, requestURI=tostring(audit.requestURI), verb=tostring(audit.verb), status=toint(audit.responseStatus.code), userAgent=tostring(audit.userAgent), user=tostring(audit.user.username),latency=datetime_diff('millisecond', todatetime(audit.stageTimestamp), todatetime(audit.requestReceivedTimestamp)), audit
| where verb in ('create') 
| where userAgent contains "kubectl"
| where requestURI contains "/pods/nsenter"


/////////// JIT audit  /////////////////////////
https://dataexplorer.azure.com/clusters/aks/databases/AKSprod?query=H4sIAAAAAAAAA21P20rDQBB971fMU5NAamNUpMUIAfsQtVCa+AHb3SOuJJuwO4lE/Hg3RamoMA9zZjg3WfeOYcNAvPcWrhZNEJ0pweIgHMLgvqg8znulefZBby+woJ2F1A6VblCyaDq6zcgzwP4Qpkl6vkiuF+mKkmR9ma6TJCJh1F/Wzb+k9GJ9tfITzZbLb8Oj/WaA4WrsQFlGQdlLCSio4BRLWNHAd3EkW8NCG0fBHq7trcREzErUz4sSdtAS8wl87cdn/lDOcy/q3CMG1FmuGm20Yyu4tZNLZ9tXSKaq2G7KKt/uYqpghOGYnhxsoXw+zWP8I0hMd77iVDn+VcLrudYyHcaT3iebSdwBiwEAAA==

cluster('azureslam').database('JIT').Audit
| where PreciseTimeStamp >= datetime(2021-07-29 00:42:00) and PreciseTimeStamp < datetime(2021-07-29 23:59:59)
//| where AuditEventType == 'Succeeded'
| where Parameters contains 'ResourceType=Self-Service&SelfServiceType=AKS&AccessLevel=Administrator'
| project TIMESTAMP, Tenant, UserIdentity, Parameters, DateTime, AuditEventType
| sort by TIMESTAMP


/////////// AKSProd Trace table /////////////////////////

https://dataexplorer.azure.com/clusters/aks/databases/AKSprod?query=H4sIAAAAAAAAA32QwU7DMBBE73zF4hOVUsU1INSIwAEuOSCh0n6AcVax28QO602REB+P1UpJpVZIPu3Om5l15U3onG9W+DVg5DVpg1e/8G2REN4JjYu4dh1+sO56eCqh1oycBjdKqsVcPszVEqQs7lQh5Qy0r8+px4uQui3ul+nNxjivO4x9KgBlCWLr2Ca7FkmMijh8RkOuZxd89QrXSSYOmaypQd6sqsMst6hbtj/HXSrBQ3wJNR6B0W2CTPCsnY8JbUh7ft5EpFLkOQS6LCOMod2j+EewDzucwk5apOuUlGnTU9ii4bMfyybLDCxz/4ZsQ52dmCSa9Q5hIf8A0bJZYMIBAAA=

IncomingRequestTrace
| where PreciseTimeStamp >= datetime(2021-07-29 00:42:00) and PreciseTimeStamp < datetime(2021-07-29 23:59:59)
| where namespace == "jithandler"
| where subscriptionID != "" and targetURI != "/healthz" and StatusCode != ""
| where targetURI contains "/grant?User="// or targetURI contains "/resolve" or targetURI contains "/revoke"
| where StatusCode == 200
| project PreciseTimeStamp, targetURI, httpMethod, StatusCode
| take 10



/////////////////////////
// ARM
/////////////////////////


// Query resource table in ARM
// For ACS v1 resources
cluster('armprod').database("CosmosToKusto").ResourcesTable
| summarize max(SnapshotDate)
| join ResourcesTable on $left.max_SnapshotDate==$right.SnapshotDate
| where ResourceId contains "Microsoft.ContainerService/containerService"
| distinct SubscriptionId, ResourceGroupName, ResourceId

union cluster('armprod').database('ARMProd').HttpIncomingRequests, 
      cluster('armprod').database('ARMProd').HttpOutgoingRequests
| where TIMESTAMP between (datetime(2019-09-03)..ago(1d))
| where httpStatusCode <> -1
| where operationName == "PUT/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS/"
| where exceptionMessage contains "A task was canceled"
| where subscriptionId == "b0d50d34-4247-4cae-871a-6b1799907b8d"
| count 

union cluster('armprod').database('ARMProd').HttpIncomingRequests, 
      cluster('armprod').database('ARMProd').HttpOutgoingRequests
| where TIMESTAMP > ago(5d)
| where httpStatusCode <> -1
| where operationName == "PUT/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS/"
| where exceptionMessage contains "allocationfailure"
| take 1 


union cluster('armprod').database('ARMProd').HttpIncomingRequests, 
      cluster('armprod').database('ARMProd').HttpOutgoingRequests
| where TIMESTAMP > ago(5d)
| where httpStatusCode == 429
| where subscriptionId == '13b78706-0ca6-42fe-9dee-7a05c0396391'
| where operationName == "PUT/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.NETWORK/NETWORKSECURITYGROUPS/SECURITYRULES/"
| where targetUri contains 'rbac1'
| project TIMESTAMP, targetUri, userAgent, referer, additionalProperties, hostName, principalOid, clientApplicationId, clientIpAddress

| summarize count() by userAgent

cluster('armprod').database('ARMProd').Errors
| where TIMESTAMP  > ago(1d)
| where exception contains "allocationfailure"

// Storage failures
cluster('armprod').database('ARMProd').Errors
| where Role == "StorageOperations.Replicator.Platform.razzle"
| where TIMESTAMP  > ago(1d)
| where exception contains "The remote server returned an error: (503) Server Unavailable."
| summarize count() by bin(TIMESTAMP, 10m)
| render  timechart 

cluster('armprod').database('ARMProd').Errors
| where Role == "StorageOperations.Replicator.Platform.razzle"
| where TIMESTAMP  > ago(1d)

//Replace XXXX below with your namespace value in lowercase
//Change the period to what you desire but note that the query will time out if you choose a large time period
cluster('armprod').database('ARMProd').OutgoingRequestsToRP_V2(ago(15m), now())
    | extend regionType = getRegionType(Provider, hostName, subscriptionId, targetUri)
    | where Provider == "microsoft.containerservice"
    | summarize
    TotalRequest=count(),
    Success = countif(httpStatusCode >= 200 and httpStatusCode < 400),
    ServerFailure=countif(httpStatusCode == 408 or httpStatusCode >= 500),
    ClientFailure=countif(httpStatusCode >= 400 and httpStatusCode < 500 and httpStatusCode != 408),
    CanaryCount = countif(regionType=='Canary'),
    ProdCount = countif(regionType=='Prod'),
    TestCount = countif(regionType== 'Test')
    by
    bin(TIMESTAMP, 1d), Provider, operationName, apiVersion, regionType, PotentialNoise  
    | where PotentialNoise != 1
| project 
    OperationName = operationName,
    Provider, 
    APIVersion = apiVersion,
    TIMESTAMP,
    Region = regionType,
    TotalRequest,
    Success,
    ServerFailure,
    ClientFailure,
    CanaryCount,
    ProdCount,
    TestCount

// Get error message for an ARM call in Async path
cluster('armprod').database('ARMProd').EventServiceEntries 
| where TIMESTAMP > ago(2h)
| where subscriptionId == 'c4c3550e-a965-4993-a50c-628fd38cd3e1'
| where status == "Failed"
| project statusmessage = parse_json(properties).statusMessage 
| extend innerstatus = parse_json(tostring(parse_json(tostring(statusmessage)).error)).code, parse_json(tostring(statusmessage)).code  
| extend message = parse_json(tostring(parse_json(tostring(statusmessage)).error)).message, parse_json(tostring(statusmessage)).message

// Get not found errors for listClusterUserCredential action
cluster('armprod').database('ARMProd').EventServiceEntries 
| where TIMESTAMP >= ago(7d) 
| where resourceProvider =~ "Microsoft.ContainerService" 
| where operationName =~ "Microsoft.ContainerService/managedClusters/listClusterUserCredential/action" 
| where subStatus =~ "NotFound"  
| extend statusmessage = parse_json(properties).statusMessage 
| extend innerstatus = iif(parse_json(tostring(statusmessage)).code=="", parse_json(tostring(parse_json(tostring(statusmessage)).error)).code, parse_json(tostring(statusmessage)).code)  
| extend message = iif(parse_json(tostring(statusmessage)).message=="", parse_json(tostring(parse_json(tostring(statusmessage)).error)).message, parse_json(tostring(statusmessage)).message) 
| where innerstatus =~ "ResourceGroupNotFound" or innerstatus =~ "ResourceNotFound"  
| join (
    HttpIncomingRequests 
    | where TIMESTAMP > ago(7d) 
    | where authorizationAction  =~ "Microsoft.ContainerService/managedClusters/listClusterUserCredential/action" ) 
  on correlationId 
| summarize count() by failureCause 


//////////////////////
// vmainsight, VMALENS
/////////////////////

// VM down state
 let start = datetime(5/20/2020);
 let end = now();
  cluster('vmakpi').database('vmadb').VMALENS
| where StartTime between (start .. end)
| where LastKnownSubscriptionId == '30a25c0e-1b63-4aa3-9240-834cf5725970' and AvailabilityState == 'Down'
| project StartTime, Cluster, NodeId, TenantId, ContainerId, ResourceId, LastKnownSubscriptionId, RCALevel2

// Get all node state transitions for a host
// OneFleet Node
let host="fd35cbc3-b300-4599-a7f4-9a9da73e148e";
cluster('vmainsight').database('vmadb').NodeStateTransitions
| where NodeId == host

//////////////////////
// rdos. https://rdos.kusto.windows.net/rdos 
// vm instance health and host health
/////////////////////

//
// writeback blips (High Io latencies)
//
let startTime = ago(60d);
let endTime = ago(1h);
cluster('Vmakpi').database('Air').AirDiskIOBlipEvents
| where EventTime between (startTime .. endTime)
| where BlackoutRCA contains "Blackouts.Xstore.Writeback.Writeback"
| summarize WriteBackNodeCount = dcount(NodeId), WriteBackVmCount = dcount(ContainerId) by bin(EventTime, 1d) //, BlackoutRCA


cluster('rdos').database('rdos').ImdsApiRequests(12h)
| where Container == "66afd627-d212-44e3-abb5-cc09775b7b58"

cluster('rdos').database('rdos').NodeServiceEventEtwTable 
| where NodeId == "67e79876-927a-4c42-b0a4-08319e5f3a04" or NodeId == "1cbf5903-f3b5-4bdc-b575-7d3e29225b77"
| where Message contains "StorageBlobLeasePending"
| where PreciseTimeStamp > ago(1d)
| project PreciseTimeStamp, Message

cluster('rdos').database('rdos').NodeServiceEventEtwTable 
| where Message contains "StorageBlobLeasePending"
| where PreciseTimeStamp > ago(10h)
| where Cluster contains "AM5PrdApp36"
| parse Message with "Container[" containerId "]" *
| summarize by containerId
| join cluster('azurecm.kusto.windows.net').database('AzureCM').LogContainerHealthSnapshot on containerId
| where containerState !contains "ContainerStateStarted" 
| summarize by containerId, containerState

// Get health issue for one vm
// vmid is called: ContainerId
cluster('rdos').database('rdos').VmHealthRawStateEtwTable
| where ContainerId == "fed82c78-f48d-419a-9238-c253fbcd15eb"
| where PreciseTimeStamp > ago(12h)


/////////////////////////////////////////////////////////////////////////////////////
// vmainsight: host and vm runtime info
/////////////////////////////////////////////////////////////////////////////////////

// Get all node state transitions for a host
// OneFleet Node
let host="fd35cbc3-b300-4599-a7f4-9a9da73e148e";
cluster('vmainsight').database('vmadb').NodeStateTransitions
| where NodeId == host

// Check host (bare metal) CPU usage
cluster('vmainsight').database('vmadb').HighCpuCounterNodeTable
| where NodeId == "33395e2a-f188-42e2-a9a3-6dd21a08453c"
    and PreciseTimeStamp > datetime(2019-09-24 00:00:00) 
    and PreciseTimeStamp < datetime(2019-09-26 23:59:59)

cluster('vmainsight').database('vmadb').VMA
| take 1


cluster('vmainsight').database('Air').
GetAzureCoreRCA(ago(6h),ago(1h), "d3445265-eef0-4cf5-9adb-7abe22f2e180")



//////////    AzureCM        //////////////
cluster('azurecm').database('AzureCM').NodeStateChangeDurationDetails
| where PreciseTimeStamp >=  ago(2d) 
| where [@'nodeId'] == @'33395e2a-f188-42e2-a9a3-6dd21a08453c'

// Map from vmname to vmid, nodeid etc.
// Find vmid (called ContainerId) from vm name (called: roleInstanceName)
cluster('azurecm').database('AzureCM').LogContainerSnapshot
| where tenantName contains "1d5017fa-c73d-4db3-92a8-192c896a486a"
| where roleInstanceName contains "k8s-master-18879312-1"
| where PreciseTimeStamp > ago(3d)
| summarize arg_max(PreciseTimeStamp, *) by containerId
//| project containerId, roleInstanceName







